version: '3.7'

services:
  app:
    tty: true
    stdin_open: true
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle && bundle exec rake db:migrate && bundle exec rails s -p 3000 -b '0.0.0.0'"
    environment:
      DATABASE_URL: postgresql://postgres:postgres@postgres/accounts
    volumes:
      - .:/app
    ports:
      - 3000:3000
    depends_on:
      - postgres

  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: accounts
    volumes:
      - attributes_postgres:/var/lib/postgresql/data

volumes:
  attributes_postgres:
