---
resources:
  - name: git-main
    type: git
    icon: github-circle
    source:
      uri: git@github.com:alphagov/govuk-attribute-service-prototype.git
      branch: main
      private_key: ((concourse_ci_github_ssh_read_only))

  - name: git-main-gems-dockerfile
    icon: github-circle
    type: git
    source:
      uri: git@github.com:alphagov/govuk-attribute-service-prototype.git
      branch: main
      private_key: ((concourse_ci_github_ssh_read_only))
      paths:
        - concourse/Dockerfile
        - Gemfile*

  - name: every-day
    type: time
    source:
      interval: 24h

  - name: tests-image
    type: docker-image
    icon: docker
    source:
      repository: ((readonly_private_ecr_repo_url))
      tag: govuk-attribute-service-tests-image

jobs:
  - name: update-pipeline
    plan:
      - get: git-main
        trigger: true
      - set_pipeline: govuk-attribute-service-prototype
        file: git-main/concourse/pipeline.yml

  - name: build-tests-image
    serial: true
    build_log_retention:
      builds: 100
    plan:
      - get: every-day
        trigger: true
      - get: git-main-gems-dockerfile
        trigger: true
      - put: tests-image
        params:
          build: git-main-gems-dockerfile
          dockerfile: git-main-gems-dockerfile/concourse/Dockerfile

  - name: run-quality-checks
    serial: true
    plan:
      - get: tests-image
        passed:
          - build-tests-image
        trigger: true
      - get: git-main
        trigger: true
      - task: run-tests-task
        image: tests-image
        config:
          inputs:
            - name: git-main
          outputs:
            - name: committer-details
          platform: linux
          run:
            dir: git-main
            path: bash
            args:
              - -c
              - |
                set -eu
                service postgresql start
                su - postgres -c "psql -c \"create role root with createdb login password 'password';\""
                export TEST_DATABASE_URL="postgres://root:password@localhost:5432/accounts"
                bundle install
                bundle exec rails db:setup
                bundle exec rails db:migrate
                bundle exec rake
  - name: deploy-app-staging
    serial: true
    plan:
      - get: git-main
        trigger: true
        passed: [run-quality-checks]
      - task: deploy-to-paas
        file: git-main/concourse/tasks/deploy-to-govuk-paas.yml
        params:
          CF_ORG: govuk-accounts
          CF_APP_NAME: govuk-attribute-service
          CF_SPACE: staging
          CF_STARTUP_TIMEOUT: 15 # minutes
          APP_INSTANCES: 1
          HOSTNAME: govuk-attribute-service-staging
  - name: deploy-app-production
    serial: true
    plan:
      - get: git-main
        trigger: true
        passed: [ping-test-staging]
      - task: deploy-to-paas
        file: git-main/concourse/tasks/deploy-to-govuk-paas.yml
        params:
          CF_ORG: govuk-accounts
          CF_APP_NAME: govuk-attribute-service
          CF_SPACE: production
          CF_STARTUP_TIMEOUT: 15 # minutes
          APP_INSTANCES: 1
          HOSTNAME: govuk-attribute-service
