platform: linux
image_resource:
  type: docker-image
  source:
    repository: governmentpaas/curl-ssl
run:
  path: sh
  args:
    - '-c'
    - |
      set -eu
      echo "$MESSAGE"
      curl --fail --silent --verbose "$URL"
